name: pgscatalog-utils
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=75.1
  - ld_impl_linux-64=2.45
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.11.12
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - isal==1.8.0
      - joblib==1.5.2
      - natsort==8.4.0
      - numpy==1.26.4
      - pandas==2.2.3
      - pgscatalog-calc==0.3.1
      - pgscatalog-core==1.0.1
      - pgscatalog-match==0.4.0
      - polars==0.20.30
      - pyarrow==15.0.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyliftover==0.4.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - xopen==2.0.2
      - zlib-ng==1.0.0
      - zstandard==0.25.0
