name: report
channels:
  - conda-forge
  - defaults
dependencies:
  - r-dplyr
  - r-dt
  - r-tidyr
  - r-ggplot2
  - r-forcats
  - r-readr
  - r-purrr
  - r-jsonlite
  - r-data.table
  - quarto=1.3.433
  - r-rmarkdown
  - r-r.utils
